{% set name = "Events" %}
{% set version = "0.4" %}
{% set sha256 = "01d9dd2a061f908d74a89fa5c8f07baa694f02a2a5974983663faaf7a97180f5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - events

about:
  home: http://github.com/pyeve/events
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Event Handling the C# Style
  description: |
    Bringing the elegance of C# EventHandler to Python
  doc_url: https://events.readthedocs.org
  dev_url: http://github.com/pyeve/events

extra:
  recipe-maintainers:
    - holgern
