travis:
  secure:
    BINSTAR_TOKEN: FE1LAb8BeTpRALesXuOsw/nMT0IKx79Lz6YYxE3NLGZmUS0j2KGD8tF+m3IlRYXEdpIKeLWhs+uCsR89QBENgRcbOOOUVaIL7dbLcW9lpQjjPiIz3ELOU0VU6bi5YwKgoIMkHOMZwsHcW65OOhttxVwJL4duIdtqWdLlNPvMgowmpra38VX0abGZxalTasTMLpgOMz8uqigCN/OjnSGIGqeRpVkaEB7x1cDf30WLwz8VqErYR3wDOhZfT6lh12a/JPHxKtfYL6NeCyUO0GdCijXoZ/9K00dz1UF8jFRhhNGjknY8H8f5egjnHC2ffurDdEVPPH44y+KTWVdlsFLZC8dxDBnW2KwPMWPpvpP/57mKoccDVGPBjQcA2diYwyLAFDSN9T7vDjm1T7x3w3oZ4H3uUG2fyLrJEXLiYhNayX+Npg61wWYk3t/cl/+IBBJCEMkdiZ8ENfr67fzwsBNqSuzYniqY/XG2kGcN/GY6i+/Og3FMdJtajNtVZzxA5H56i5DwvKJtiL8TiXhPQHW7xScJfoxoyY8Yr72yA6cXyfmy2KpBdYjEVQIexxurqwEOKJ9WQj7tBVtiQoWO7qa2wLZeqQjDgvEJtx3PFFsL8X8mrFIpiN4KSXeq4n0H24hOB15v6Iyvn7HJvFGaRsgPecDm+dsWU/FbiSvK1i0NgoU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
