travis:
  secure:
    BINSTAR_TOKEN: SxRHxqS1FrTozTyqQ9Fa7QT4VWrDUaJ9K63tWrXP/EKUGEiBxnWmICrM9KjChFSRzyVP8EWYgqs/XvTVvjBcQujJLOf53C1JJB2KNaPKwZPOLJHQ61KScDMgynvSOvE5u8ySEcdAcSiOnDvY66cH+zdIOY9szRsLh4VrclkjjYLjGHcUxI6p2utrMdg1ND4vw8jBh8eCgzXPPNbdxe4Y6DTJDM1JKHEzZP2tNy8p+8A1QViIJBROKbBVpCriYoPuYxDiq4CQg939J5JjACvoYUFaQrb7zB0tiXgG2QcAW5kyWNaEV6DXK1rT4DAmzOZ3a+i+ZtLzUdmI47Qc16FTa2Bf9G3GuNwK2gLpgbnl69RfCEBQacRxcZHnSgAWk1Aa2Rp1q0GYHL5KVBIXFQcBS6QR87SKIOTmV7KgT0+eyNLL05KE1NS78vxkEcrX5kEy3iHOZUkB2cwcB2quy8nX01aU8I5QBF8memJfE8v07LNi1tFlhePtsYAR8JCka+meP0oCZcuF/Bg5zdThg6cG6NTbKuX5uv7FwXBg5tWehQzoe/NtLmlxr08lFHfJHqZjWPeEa3d9m3IQnta25cagVVxBu2/FI8xwShojJG+Y+j2L7C1/YgJt84fA1Vyekq4pRrmmnZmWhxaBVI9lqz72FmisP+/zF3TXwJza6jyTzxc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
