travis:
  secure:
    BINSTAR_TOKEN: YKJMz+vAt5rLILk/ib+8VBCBhjngIe1Ag2iXz2j8CY5ovhjwKCH9b33P7HLqhGQCm14NZN+5lGGYSecIBqF3CUXs7cufTSla/79GWMBSUNFJG+Wppks5T3UEF7m9hHo3whMZARI2Su3CpE54mJjlVeqFSQ9dw95E0qiS0LR/iVRMjooLq46vueKhyQMQqcNmkf7PCE3m52+1KUg4jeNmt8Fmd32DWESmyKckaX3tNmPGPD3whNVRCb/bhaxejIvx5kzCgCgLFCgrfwx3QXwEMiAfsY6shL534Xq+paeSleOY1xtVbGbxnykTzapjf5eMjprvyyGALZF1BjupXul3xtLJWBLN0XdJgqfjGtdf+FB7DHYXbAzXFZfIqxRIsxWUlKnbV+p4eX7cpPB7xYfManioK6Isl4kX0vU/5FbnI7bI+jIJVggh+wQmqiEFm89xllr/qLujA9jeJSo9M1j7fvsLmU3aFb+PfjmmGQFu7ajBZtSw7lDmQRiXMlpAq1m3LaRcrgcte8uBg0TNK58iJap15NdA10wyoYVXIvK8Fl/2Q+5xQOSx6oVtQao3Q3Ig9qieI2NxkJZvpwJUv0J6weXcwhiT+f2NX9hG61ziW1oZJGQ3Z/sps0CpP24tqn7f1/D/RglFIRAHFQHjJJG6gkf553LJeMBhsnGPr0JRZ8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
